CREATE TABLE "Tokens" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Content"	TEXT NOT NULL,
	"DocumentId"	INTEGER NOT NULL,
	CONSTRAINT "PK_Tokens_Id" PRIMARY KEY("Id" AUTOINCREMENT),
	CONSTRAINT "FK_Documents_Id" FOREIGN KEY (DocumentId) REFERENCES Documents (Id)
)
